name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/*

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      python_ver: '3.12.1'

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python ${{ env.python-ver }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.python-ver }}
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt -t ./lib
          zip -r Flow.Launcher.Plugin.SugarCalc.zip . -x '*.git*'
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: 'Flow.Launcher.Plugin.SugarCalc.zip'
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
